/*
 *  		MAG - A Dungeon Adventuring Game
 *
 *	Copyright (C) 1986,87,88 by Michael J. Teixeira
 *
 *  General permission to copy or modify, but not for profit, is hereby
 *  granted, provided that the above copyright notice is included.
 *
 */

/* this file contains the definitions for the perm object table */

#define		FOODRAT		0
#define		SLIMEMOLD	1
#define		CHEESE		3
#define		MUSHROOM	6

#define		BLINDNESS	7
#define		CONFUSION	8
#define		EXTRAHEAL	9
#define		GAINSTR		10
#define		HASTESELF	11
#define		HEALING		12
#define		HEROISM		13
#define		INVISIBILITY	14
#define		MAGICDET	15
#define		MONDETECT	16
#define		PARALYSIS	17
#define		POISON		18
#define		RAISELEV	19
#define		RESTORESTR	20
#define		PSEEINV		21
#define		SELFPOLY	22
#define		THIRST		23
#define		DELUSION	24
#define		LEVITATION	25
#define		ACID		26

#define		SAGGMON		27
#define		NEGATION	28
#define		CONMON		29
#define		CREATEMON	30
#define		TREASFIND	31
#define		ENCHARM		32
#define		ENCHWEP		33
#define		GENOCIDE	34
#define		HOLDMON		35
#define		IDENTIFY	36
#define		CONTLIGHT	37
#define		MAGICMAP	38
#define		REMCURSE	39
#define		RESTCHARGE	40
#define		SCAREMON	41
#define		SLEEP		42
#define		TELEPORT	43
#define		OBJATTRACT	44
#define		DETECTFOOD	45
#define		GALVANIZE	46
#define		LABYRINTH	47

#define		DRAINLIFE	48
#define		ILLUMINATION	49
#define		WONDER		50
#define		SLOWMON		51
#define		POLYMORPH	52
#define		MONINVIS	53
#define		DIGGING		54
#define		CURING		55
#define		FEAR		56
#define		STRIKING	57
#define		FIRE		58
#define		FROST		59
#define		TELEAWAY	60
#define		TELETO		61
#define		CANCEL		62
#define		LIGHTNING	63
#define		TRAPDET		64
#define		HASTEMON	65
#define		WMAGDET		66
#define		MAGMIS		67
#define		WPARALYSIS	68

#define		DECRDAM		69
#define		DECRHP		70
#define		VULNERABILITY	71
#define		WEAKNESS	72
#define		FUMBLING	73
#define		AGGMON		74
#define		RTELEPORT	76
#define		FREEACT		77
#define		SUSTAINSTR	78
#define		REGEN		79
#define		SEARCHING	80
#define		SEEINVIS	81
#define		STEALTH		82
#define		WARMTH		83
#define		FIRERES		84
#define		SUSTINANCE	85
#define		RESURRECTION	86
#define		MAGABSORB	87
#define		RANDOMNESS	88
#define		ADDSTR		89
#define		DEXTERITY	90
#define		INCRDAM		91
#define		INCRHP		92
#define		PROTECTION	93

#define		ARROW		94
#define		LONGBOW		95
#define		BOLT		96
#define		CROSSBOW	97
#define		BULLET		98
#define		SLING		99
#define		DAGGER		100
#define		DART		101
#define		FLAIL		102
#define		HANDAXE		103
#define		MACE		105
#define		BOULDER		106
#define		SPEAR		107
#define		TWOHAND		108

#define		BANDED		109
#define		CHAIN		110
#define		COCONUT		111
#define		PADDED		113
#define		PLATE		114
#define		SCALE		116
#define		STUDLEATHER	118

#define		BUCKLER		119
#define		MEDIUM		120
#define		MITHRIL		122

#define		COPPER		123
#define		KSILVER		124
#define		GOLDEN		125
#define		SKELETON	126

#define		SAPPHIRE	127
#define		COMPASS		128
#define		CROSS		129
#define		MIRROR		130
#define		OILFLASK	131
#define		TINDERBOX	132
#define		ETHEREAL	133
#define		CHIME		134

#define		SPARKLING	135

#define		PLATINUM	147
#define		GOLD		148
#define		ELECTRUM	149
#define		SILVER		150
